[package]
name = "gold-structures"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
rand = "0.8.5"
secp256k1 = { version = "0.30.0", features = ["hashes", "rand"] }
thiserror = "2.0.9"
